### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by servusdei2018** [RohanSreelesh/School_Project_CRM#1]
A good `README.md` is needed, one that summarizes your repository. This looks like a promising project, and I'd love to help out!

**Comment by RohanSreelesh** [comment]
Yes you're right we will add a good README.md soon. Great to hear about your interest in our project but this is a school project so we can't accept any outside help as of now sorry.

**Comment by saintwithataint** [comment]
Bahaut sahi 👌

**Comment by RohanSreelesh** [comment]
😂😂😂😂
